# -*- coding: utf-8 -*-
"""AliH4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HAOmtX1AUeFqke1HP6t5S4IlgrxWYWkY

### Conditional Statements Lectures
"""

if None:
  print ("True is the condition.")
else:
  print("None is false")

if float:
  print("True")

if 'x' in ["x","xxx","y"]:
  print("X is found")

if ('al' in "Ali") or ('y' in "yellow"):
  print("1")

x = -0.00001
if x > 0:
  print("Positive")
elif x == 0:
  print("Zero")
else:
  print("Negative")

